### ISSUE TITLE
Kabel hansen 5D-FB

### ISSUE THREAD

**Issue by sp9rqa** [olgierd/coaxcalculator#10]
5D-FB-Hansen:
  name: 5D-FB
  manufacturer: HANSEN
  type: 5D-FB
  attenuation: {100:6.3, 150:7.8, 280:10.8, 350:12.1, 400:13.0, 800:18.9, 900:  +20.2, 1200:23.7, 1500:26.8, 1800:29.7, 1900:30.6, 2000:31.5, 2200:33.3, 2500:  +35.8}
  data_source: https://www.caledonian-cables.co.uk/Coaxia_Cable/50Ohm%20RF/5D-  +FB.html
  additional_info:
    ext_diametr_mm: 7.5
    velocity_factor: 0.82
    impedance: 50

**Comment by canislupus11** [comment]
https://github.com/olgierd/coaxcalculator/pull/11

**Comment by sp9rqa** [comment]
Skrypt nie radzi sobie z wartościami mocy poniżej 1[W]. Ustawienie wartości mocy 0.1[W] daje zawsze wynik 0.00 bez względu na pozostałe wartości. Chciałem sprawdzić ile będę miał straty na module Lory przy 100mW i tak mi wyszło przy okazji. Skoro wynik jest do 2-ch miejsc po przecinku to wynik powinien jeszcze się zmieścić przynajmniej na drugiej pozycji.

**Comment by olgierd** [comment]
Poprawione. TIP: tłumienie dla 100W jest takie samo jak 100mW, więc wpisując wartość w mW, dostaniemy wynik w mW ;-)
